    <div class="back_to_top">
				<p id="back"><button id="back_to_top">Back To Top</button></p>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-6">
						<h4>Support</h4>
						<p>My Booking</p>
						<p>FAQ</p>
						<p>Contact us 24/7</p>
						<p>Our Guarantee</p>
					</div>
					<div class="col-6">
						<h4>Partnership</h4>
						<p>Affiliate Program</p>
						<p>Travel Partners</p>
						<p>Offer for Bloggers</p>
					</div>
					<div class="col-6">
						<h4>TDN Payment Products</h4>
						<p>TDN Business Card</p>
						<p>Hire with Points</p>
						<p>Reload your Balance</p>
					</div>
				</div>
			</div>
		</footer>