    <meta charset="utf-8" />
	<meta name="description" content="Creating Web Applications" />
	<meta name="keywords"		content="HTML, CSS, JavaScript"	/>
	<meta name="author"			content="Tien Duc Nguyen"	/>
	<script src="scripts/enhancement1.js"></script>
	<link rel="stylesheet" href="styles/style.css">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">