<div class="header">
	<div class="container">
		<div class="navbar">
		<div class="logo">
			<img src="images/tdn_logo.png" alt="logo" >
		</div>
			<nav id="na">
				<ul>
					<li><a href="index.php">Home</a></li>
					<li><a href="product.php">Products</a></li>
					<li><a href="enquire.php">Enquire</a></li>
					<li><a href="about.php">About</a></li>
					<li><a href="manage.php">Manage</a></li>
					<li><a href="enhancement.html">Enhancement</a></li>
					<li><a href="enhancement2.html">Enhancement2</a></li>
					<li><a href="enhancement3.php">Enhancement3</a></li>
				</ul>
			</nav>	

		</div>
	</div>
	<div class="row">
		<div class="col-2">
			<h1><strong>TOGETHERWETRAVEL</strong><br><strong></strong></h1>
			<p>Best company in the field of car rental.</p>
			<a href="product.html" class="expl">Explore Now &#8594;</a>
		</div>
		<div class="col-2">
			<img src="images/vinfastindex.jpg" alt="vin" >
		</div>
	</div>
	
</div>