<div class="header2">
	<div class="container">
		<div class="navbar">
		<div class="logo">
			<img src="images/tdn_logo.png" alt="logo">
		</div>
			<nav id="na">
				<ul>
					<li><a href="index.php">Home</a></li>
					<li><a href="product.php">Products</a></li>
					<li><a href="enquire.php">Enquire</a></li>
					<li><a href="about.php">About</a></li>
					<li><a href="manage.php">Manage</a></li>
					<li><a href="enhancement.php  ">Enhancement</a></li>
					<li><a href="enhancement2.php">Enhancement2</a></li>
					<li><a href="enhancement3.php">Enhancement3</a></li>
				</ul>
			</nav>		

		</div>
		
	</div>
</div>